In [31]:
import pandas as pd
df=pd.read_csv('marucraft_starter_order_lines.csv')
df.head(3)

,order_id,product_id,quantity,unit_price_inr,unit_cost_inr,order_date,customer_id,sales_channel,payment_method,order_status,...,reorder_lead_days,customer_city,customer_state,customer_segment,signup_date,acquisition_channel,gross_item_sales_inr,discounted_item_revenue_inr,item_cost_total_inr,estimated_item_gross_profit_inr
0,MC00001,P023,1,672.99,260,2024-01-01,C0541,Marketplace,UPI,Returned,...,20,Ahmedabad,Gujarat,Returning,2023-06-03,Instagram,672.99,572.0415,260,312.0415
1,MC00002,P024,1,601.58,230,2024-01-01,C0563,Marketplace,Cash on Delivery,Cancelled,...,16,Udaipur,Rajasthan,New,2023-11-06,Organic Search,601.58,451.1850,230,221.1850
2,MC00003,P025,1,1549.25,620,2024-01-01,C0365,Website,Net Banking,Delivered,...,18,Bengaluru,Karnataka,New,2024-05-09,Marketplace,1549.25,1471.7875,620,851.7875

In [32]:
df.shape

(4470, 27)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4470 entries, 0 to 4469
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   order_id                         4470 non-null   str
 1   product_id                       4470 non-null   str
 2   quantity                         4470 non-null   int64
 3   unit_price_inr                   4470 non-null   float64
 4   unit_cost_inr                    4470 non-null   int64
 5   order_date                       4470 non-null   str
 6   customer_id                      4470 non-null   str
 7   sales_channel                    4470 non-null   str
 8   payment_method                   4470 non-null   str
 9   order_status                     4470 non-null   str
 10  discount_pct                     4470 non-null   float64
 11  shipping_cost_inr                4470 non-null   float64
 12  delivery_days                    4190 non-null   float64
 13  product_name                     4470 non-null   str
 14  category                         4470 non-null   str
 15  list_price_inr                   4470 non-null   int64
 16  supplier_region                  4470 non-null   str
 17  reorder_lead_days                4470 non-null   int64
 18  customer_city                    4470 non-null   str
 19  customer_state                   4470 non-null   str
 20  customer_segment                 4470 non-null   str
 21  signup_date                      4470 non-null   str
 22  acquisition_channel              4470 non-null   str
 23  gross_item_sales_inr             4470 non-null   float64
 24  discounted_item_revenue_inr      4470 non-null   float64
 25  item_cost_total_inr              4470 non-null   int64
 26  estimated_item_gross_profit_inr  4470 non-null   float64
dtypes: float64(7), int64(5), str(15)
memory usage: 1.5 MB

In [34]:
df.describe()

,quantity,unit_price_inr,unit_cost_inr,discount_pct,shipping_cost_inr,delivery_days,list_price_inr,reorder_lead_days,gross_item_sales_inr,discounted_item_revenue_inr,item_cost_total_inr,estimated_item_gross_profit_inr
count,4470.000000,4470.000000,4470.000000,4470.000000,4470.000000,4190.000000,4470.000000,4470.000000,4470.000000,4470.000000,4470.000000,4470.000000
mean,1.410067,801.392371,344.432886,0.110906,88.976906,5.136993,813.402237,13.788143,1126.797268,1001.850279,484.708054,517.142226
std,0.666184,479.216540,218.700948,0.072377,32.086837,2.578598,485.041054,4.680443,898.455863,805.684522,403.672943,414.120470
min,1.000000,229.440000,95.000000,0.000000,35.020000,1.000000,249.000000,6.000000,230.050000,181.695000,95.000000,86.695000
25%,1.000000,434.282500,180.000000,0.050000,61.192500,3.000000,449.000000,11.000000,537.350000,467.359750,220.000000,244.279000
50%,1.000000,659.725000,260.000000,0.100000,88.780000,5.000000,649.000000,14.000000,842.685000,743.541750,360.000000,389.061500
75%,2.000000,1029.935000,420.000000,0.150000,117.267500,7.000000,999.000000,18.000000,1441.752500,1283.778750,620.000000,655.361000
max,4.000000,2303.810000,950.000000,0.250000,144.960000,11.000000,2199.000000,21.000000,8794.360000,7914.924000,3800.000000,4114.924000

In [35]:
df.columns

Index(['order_id', 'product_id', 'quantity', 'unit_price_inr', 'unit_cost_inr',
       'order_date', 'customer_id', 'sales_channel', 'payment_method',
       'order_status', 'discount_pct', 'shipping_cost_inr', 'delivery_days',
       'product_name', 'category', 'list_price_inr', 'supplier_region',
       'reorder_lead_days', 'customer_city', 'customer_state',
       'customer_segment', 'signup_date', 'acquisition_channel',
       'gross_item_sales_inr', 'discounted_item_revenue_inr',
       'item_cost_total_inr', 'estimated_item_gross_profit_inr'],
      dtype='str')

                    DATA CLEANING

In [36]:
df['delivery_days'].isna().sum()

np.int64(280)

In [37]:
df.isna().sum()

order_id                             0
product_id                           0
quantity                             0
unit_price_inr                       0
unit_cost_inr                        0
order_date                           0
customer_id                          0
sales_channel                        0
payment_method                       0
order_status                         0
discount_pct                         0
shipping_cost_inr                    0
delivery_days                      280
product_name                         0
category                             0
list_price_inr                       0
supplier_region                      0
reorder_lead_days                    0
customer_city                        0
customer_state                       0
customer_segment                     0
signup_date                          0
acquisition_channel                  0
gross_item_sales_inr                 0
discounted_item_revenue_inr          0
item_cost_total_inr                  0
estimated_item_gross_profit_inr      0
dtype: int64

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.loc[
    df['delivery_days'].isna(),
    'order_status'
].value_counts()

order_status
Cancelled    280
Name: count, dtype: int64

In [40]:
df.dtypes

order_id                               str
product_id                             str
quantity                             int64
unit_price_inr                     float64
unit_cost_inr                        int64
order_date                             str
customer_id                            str
sales_channel                          str
payment_method                         str
order_status                           str
discount_pct                       float64
shipping_cost_inr                  float64
delivery_days                      float64
product_name                           str
category                               str
list_price_inr                       int64
supplier_region                        str
reorder_lead_days                    int64
customer_city                          str
customer_state                         str
customer_segment                       str
signup_date                            str
acquisition_channel                    str
gross_item_sales_inr               float64
discounted_item_revenue_inr        float64
item_cost_total_inr                  int64
estimated_item_gross_profit_inr    float64
dtype: object

In [41]:
df['order_date']=pd.to_datetime(df['order_date'])

In [42]:
df.rename(columns={'month_name':'year_month'}, inplace=True)

In [43]:
df.head(1)

,order_id,product_id,quantity,unit_price_inr,unit_cost_inr,order_date,customer_id,sales_channel,payment_method,order_status,...,reorder_lead_days,customer_city,customer_state,customer_segment,signup_date,acquisition_channel,gross_item_sales_inr,discounted_item_revenue_inr,item_cost_total_inr,estimated_item_gross_profit_inr
0,MC00001,P023,1,672.99,260,2024-01-01,C0541,Marketplace,UPI,Returned,...,20,Ahmedabad,Gujarat,Returning,2023-06-03,Instagram,672.99,572.0415,260,312.0415

In [44]:
df.describe()

,quantity,unit_price_inr,unit_cost_inr,order_date,discount_pct,shipping_cost_inr,delivery_days,list_price_inr,reorder_lead_days,gross_item_sales_inr,discounted_item_revenue_inr,item_cost_total_inr,estimated_item_gross_profit_inr
count,4470.000000,4470.000000,4470.000000,4470,4470.000000,4470.000000,4190.000000,4470.000000,4470.000000,4470.000000,4470.000000,4470.000000,4470.000000
mean,1.410067,801.392371,344.432886,2025-01-26 03:53:33.422818,0.110906,88.976906,5.136993,813.402237,13.788143,1126.797268,1001.850279,484.708054,517.142226
min,1.000000,229.440000,95.000000,2024-01-01 00:00:00,0.000000,35.020000,1.000000,249.000000,6.000000,230.050000,181.695000,95.000000,86.695000
25%,1.000000,434.282500,180.000000,2024-08-11 06:00:00,0.050000,61.192500,3.000000,449.000000,11.000000,537.350000,467.359750,220.000000,244.279000
50%,1.000000,659.725000,260.000000,2025-01-16 00:00:00,0.100000,88.780000,5.000000,649.000000,14.000000,842.685000,743.541750,360.000000,389.061500
75%,2.000000,1029.935000,420.000000,2025-08-04 00:00:00,0.150000,117.267500,7.000000,999.000000,18.000000,1441.752500,1283.778750,620.000000,655.361000
max,4.000000,2303.810000,950.000000,2025-12-31 00:00:00,0.250000,144.960000,11.000000,2199.000000,21.000000,8794.360000,7914.924000,3800.000000,4114.924000
std,0.666184,479.216540,218.700948,NaN,0.072377,32.086837,2.578598,485.041054,4.680443,898.455863,805.684522,403.672943,414.120470

In [45]:
print("Negative Quantity :", (df['quantity'] < 0).sum())
print("Negative Unit Price :", (df['unit_price_inr'] < 0).sum())
print("Negative Unit Cost :", (df['unit_cost_inr'] < 0).sum())

Negative Quantity : 0
Negative Unit Price : 0
Negative Unit Cost : 0

In [46]:
df['order_status'].value_counts()

order_status
Delivered     3787
Cancelled      280
Returned       226
In Transit     177
Name: count, dtype: int64

In [47]:
df = df.rename(columns={
    'unit_price_inr': 'unit_price',
    'unit_cost_inr': 'unit_cost',
    'gross_item_sales_inr': 'sales',
    'discounted_item_revenue_inr': 'revenue',
    'item_cost_total_inr': 'total_cost',
    'estimated_item_gross_profit_inr': 'profit',
    'discount': 'discount_pct',
    'list_price_inr':'list_price',
    'shipping_cost_inr':'shipping_cost'
})

In [48]:
df[['sales',
    'revenue',
    'total_cost',
    'profit']].head()

     sales    revenue  total_cost    profit
0   672.99   572.0415         260  312.0415
1   601.58   451.1850         230  221.1850
2  1549.25  1471.7875         620  851.7875
3   387.29   367.9255         160  207.9255
4   690.34   655.8230         290  365.8230

In [49]:
df.columns.tolist()

['order_id',
 'product_id',
 'quantity',
 'unit_price',
 'unit_cost',
 'order_date',
 'customer_id',
 'sales_channel',
 'payment_method',
 'order_status',
 'discount_pct',
 'shipping_cost',
 'delivery_days',
 'product_name',
 'category',
 'list_price',
 'supplier_region',
 'reorder_lead_days',
 'customer_city',
 'customer_state',
 'customer_segment',
 'signup_date',
 'acquisition_channel',
 'sales',
 'revenue',
 'total_cost',
 'profit']

In [50]:
df['margin_pct'] = (
    df['profit']
    / df['revenue']
) * 100

In [52]:
df['discount']=df['sales']-df['revenue']

In [53]:
df['is_returned'] = (df['order_status'] == 'Returned').astype(int)

In [54]:
df.head()

,order_id,product_id,quantity,unit_price,unit_cost,order_date,customer_id,sales_channel,payment_method,order_status,...,customer_segment,signup_date,acquisition_channel,sales,revenue,total_cost,profit,margin_pct,discount,is_returned
0,MC00001,P023,1,672.99,260,2024-01-01,C0541,Marketplace,UPI,Returned,...,Returning,2023-06-03,Instagram,672.99,572.0415,260,312.0415,54.548752,100.9485,1
1,MC00002,P024,1,601.58,230,2024-01-01,C0563,Marketplace,Cash on Delivery,Cancelled,...,New,2023-11-06,Organic Search,601.58,451.1850,230,221.1850,49.023128,150.3950,0
2,MC00003,P025,1,1549.25,620,2024-01-01,C0365,Website,Net Banking,Delivered,...,New,2024-05-09,Marketplace,1549.25,1471.7875,620,851.7875,57.874353,77.4625,0
3,MC00004,P014,1,387.29,160,2024-01-01,C0447,Website,Cash on Delivery,Cancelled,...,New,2023-11-29,Instagram,387.29,367.9255,160,207.9255,56.512935,19.3645,0
4,MC00004,P022,1,690.34,290,2024-01-01,C0447,Website,Cash on Delivery,Cancelled,...,New,2023-11-29,Instagram,690.34,655.8230,290,365.8230,55.780752,34.5170,0

In [59]:

df['month_name'] = df['order_date'].dt.strftime('%B')
df['quarter'] = df['order_date'].dt.quarter

In [60]:
df['month_name_year'] = df['order_date'].dt.strftime('%b-%Y')

In [61]:
df.head()

,order_id,product_id,quantity,unit_price,unit_cost,order_date,customer_id,sales_channel,payment_method,order_status,...,sales,revenue,total_cost,profit,margin_pct,discount,is_returned,month_name,quarter,month_name_year
0,MC00001,P023,1,672.99,260,2024-01-01,C0541,Marketplace,UPI,Returned,...,672.99,572.0415,260,312.0415,54.548752,100.9485,1,January,1,Jan-2024
1,MC00002,P024,1,601.58,230,2024-01-01,C0563,Marketplace,Cash on Delivery,Cancelled,...,601.58,451.1850,230,221.1850,49.023128,150.3950,0,January,1,Jan-2024
2,MC00003,P025,1,1549.25,620,2024-01-01,C0365,Website,Net Banking,Delivered,...,1549.25,1471.7875,620,851.7875,57.874353,77.4625,0,January,1,Jan-2024
3,MC00004,P014,1,387.29,160,2024-01-01,C0447,Website,Cash on Delivery,Cancelled,...,387.29,367.9255,160,207.9255,56.512935,19.3645,0,January,1,Jan-2024
4,MC00004,P022,1,690.34,290,2024-01-01,C0447,Website,Cash on Delivery,Cancelled,...,690.34,655.8230,290,365.8230,55.780752,34.5170,0,January,1,Jan-2024

In [62]:
df.to_csv('marucraft_cleaned.csv', index=False)

In [ ]:
import sys
print(sys.executable)

c:\Program Files\Python314\python.exe

In [ ]:
import sys
!"{sys.executable}" -m pip install sqlalchemy psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\Users\puroh\AppData\Roaming\Python\Python314\site-packages (2.1.6)
Requirement already satisfied: psycopg2-binary in C:\Users\puroh\AppData\Roaming\Python\Python314\site-packages (2.9.13)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\puroh\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
import getpass
import os

import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

df = pd.read_csv("marucraft_cleaned.csv")


password = os.getenv("PGPASSWORD") or getpass.getpass(
    "PostgreSQL password for user 'postgres': "
)
if not password:
    raise ValueError("A PostgreSQL password is required to load the CSV.")

connection_url = URL.create(
    drivername="postgresql+psycopg2",
    username=os.getenv("PGUSER", "postgres"),
    password=password,
    host=os.getenv("PGHOST", "localhost"),
    port=int(os.getenv("PGPORT", "5432")),
    database=os.getenv("PGDATABASE", "marucraft_project"),
)
engine = create_engine(connection_url)

df.to_sql(
    "marucraft_orders",
    engine,
    if_exists="replace",
    index=False,
)
print(f"Loaded {len(df):,} rows into marucraft_project.marucraft_orders.")

Loaded 4,470 rows into marucraft_project.marucraft_orders.

In [64]:
df.columns.tolist()

['order_id',
 'product_id',
 'quantity',
 'unit_price',
 'unit_cost',
 'order_date',
 'customer_id',
 'sales_channel',
 'payment_method',
 'order_status',
 'discount_pct',
 'shipping_cost',
 'delivery_days',
 'product_name',
 'category',
 'list_price',
 'supplier_region',
 'reorder_lead_days',
 'customer_city',
 'customer_state',
 'customer_segment',
 'signup_date',
 'acquisition_channel',
 'sales',
 'revenue',
 'total_cost',
 'profit',
 'margin_pct',
 'discount',
 'is_returned',
 'month_name',
 'quarter',
 'month_name_year']

In [65]:
df.to_sql(
    'marucraft_orders',
    engine,
    if_exists='replace',
    index=False
)

510

In [66]:
df.to_csv(r'D:\purohit\OneDrive\Desktop\cleaned_data.csv', index=False)